# Generated by Django 4.0.4 on 2022-05-01 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=2000)),
                ('brand', models.CharField(max_length=200)),
                ('retail_price', models.IntegerField()),
                ('disc_price', models.IntegerField()),
                ('image1', models.URLField(max_length=1000)),
                ('image2', models.URLField(max_length=1000)),
                ('image3', models.URLField(max_length=1000)),
                ('image4', models.URLField(max_length=1000)),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samshop.maincategory')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samshop.subcategory')),
            ],
        ),
    ]
