# Generated by Django 4.0.4 on 2022-05-05 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samshop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetails',
            name='brand',
        ),
    ]
